### ISSUE TITLE
Generating Videos with Scene Dynamics

### ISSUE THREAD

**Issue by lkffight** [neka-nat/chainer-videogan#1]
@neka-nat  I am now debugging this code, because the paper to the data set is too big, I would like to know what their format is their own collection of video, verify the views of this article. I am based on your procedures to debug, your code is all the code or only one of the source code debugging? Can you explain the code?

**Comment by neka-nat** [comment]
Hi, Ikffight.
I prepared sample data. It is not too big and shrinking the original data. 
https://drive.google.com/open?id=0B62F7fvzj48mMGpWQkVsNnNTajQ
Please try execute training by replacing the contents of this "sample_data" directory with the contents of "data" directory.

```
rm -rf data
mv sample_data data
python train.py
```

**Comment by lkffight** [comment]
@neka-nat  Would like to ask you some questions, you release the code is all or part of the source code based on the paper.

**Comment by neka-nat** [comment]
Yes, all of the source code is based on the paper and the original torch implementation.
https://github.com/cvondrick/videogan

**Comment by lkffight** [comment]
@neka-nat  Is your video dataset downloaded from the official website of the author? Do you have that part of the video based on your debugging? The author provides a single data set is too big, I now is based on the GPU version of tensorflow, reproduce your code need to pay attention to what the problem?

**Comment by neka-nat** [comment]
Yes, as written in the README, I download the original golf data with "wget" command.
The sample data prepared is part of the original data.
https://drive.google.com/open?id=0B62F7fvzj48mMGpWQkVsNnNTajQ
In order to solve the problem of too big data, not all data is kept in memory, but only the batch size is kept.
Please see DataLoader class.
https://github.com/neka-nat/chainer-videogan/blob/master/utils.py

**Comment by lkffight** [comment]
@neka-nat I have run your code tonight there is a problem that you gave me the link function error as follows:Traceback (most recent call last):
  File "D:/DeepLearning/VideoPy/chainer-videogan-master/utils.py", line 73, in <module>
    loader = VideoLoader("data/")
  File "D:/DeepLearning/VideoPy/chainer-videogan-master/utils.py", line 45, in __init__
    with open(os.path.join(root_path, 'train_list.txt'), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/train_list.txt'
 I do not know how to handle these datasets? Did you tell me which catalog you put in my dataset?

**Comment by lkffight** [comment]
@neka-nat Do you play Tencent's instant chat software? Such as qq, micro letter, or would you use TeamViewer? I would like to ask you more easily

**Comment by neka-nat** [comment]
I am sorry that I do not use chat.

There are two ways to try to train data, which one do you want to do?
The first one is using the original data, the second one is using youtube videos.
Looking at the error messages, it seems that you try to use youtube videos.
In that case, please follow the procedure below.

```bash
cd data
python download_videos.py
cd ..
python train.py -v
```
